version: "3.7"

services:
    front:
        image: dmitriyvasil1986/deutsch_front:latest
        restart: "no"
        volumes:
            - ./static/js:/app/static/js

    db:
        image: mysql:latest
        restart: "always"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
        volumes:
            - ./mysql:/var/lib/mysql

    back:
        image: dmitriyvasil1986/deutsch_back
        restart: "always"
        environment:
            DB_PASSWORD: ${DB_PASSWORD}
            DB_USER: ${DB_USER}
            DB_NAME: ${DB_NAME}
            DB_HOST: ${DB_HOST}
            SECRET: ${SECRET}
            DEBUG: ${DEBUG}
        depends_on:
            - db
        volumes:
            - ./static:/app/static

    nginx:
        image: dmitriyvasil1986/certbot:latest
        restart: "always"
        environment:
            DOMAIN: ${DOMAIN}
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./static:/static
            - ./nginx/nginx.conf:/app/nginx.conf
        depends_on:
            - back
